config/routes.rb
Micahraejames::Application.routes.draw do
  get 'social' => 'pages#social'

  get 'contact' => 'pages#contact'

  get 'downloads' => 'pages#downloads'

  get 'media' => 'pages#media'

  get 'blog' => 'pages#blog'

  root :to => 'pages#bio'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def bio
  end

  def social
  end

  def contact
  end

  def downloads
  end

  def media
  end

  def blog
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	
	<div class="navbar navbar-fixed-bottom">
	  <div class="navbar-inner">
	    <div class="container">
	 
	      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
	 
	      <!-- Be sure to leave the brand out there if you want it shown -->
	      <a class="brand" href="http://micahraejames.com">Micah Rae James</a>
	 
	      <!-- Everything you want hidden at 940px or less, place within here -->
	      <div class="nav-collapse collapse">
	      	<ul class="nav">
		        <li><%= link_to "Bio", root_path %></li>
				<li><%= link_to "Social", social_path %></li>
				<li><%= link_to "Blog", blog_path %></li>
				<li><%= link_to "Contact", contact_path %></li>
				<li><%= link_to "Downloads", downloads_path %></li>
				<li><%= link_to "Media", media_path %></li>
			</ul>

			<ul class="nav pull-right">
				<li><%= link_to "nbjames.com logo", "http://nbjames.com"%></li>
	      </div>
	 
	    </div>
	  </div>
	</div>

<small>
	Copyright 2013. All Rights Reserved. Creative Commons>
</small>

</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="http://micahraejames.com">Micah Rae James</a>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	<ul class="nav">
	        <li><%= link_to "Bio", root_path %></li>
			<li><%= link_to "Social", social_path %></li>
			<li><%= link_to "Blog", blog_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "Downloads", downloads_path %></li>
			<li><%= link_to "Media", media_path %></li>
		</ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Micah Rae James</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

		<%= render 'layouts/header' %>
		
		<div class="container">

	<%= yield %>

		<%= render 'layouts/footer' %>

	</div>

		</body>
</html>

app/views/pages/bio.html.erb
<h2>Experience</h2>
<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

</p>
<h2>Education</h2>
<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

</p>
<h2>Personal</h2>
<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

</p>

app/views/pages/blog.html.erb
<h1>Blog</h1>
<p>Link to wordpress blog</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>For More Information about booking me for your upcoming event fill out the form below and I'll get back with you asap</p>

app/views/pages/downloads.html.erb
<h1>Downloads</h1>

<div class="row">
  <div class="span4">
  	<h2>Event Info</h2>


  </div>
  <div class="span5">
  	<h2><a href="#">Link to a file</a></h2>
  	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  	
  </div>
</div>

<div class="row">
  <div class="span4">
  	<h2>Event Info</h2>


  </div>
  <div class="span5">
  	<h2><a href="#">Link to a file</a></h2>
  	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  	
  </div>
</div>

<div class="row">
  <div class="span4">
  	<h2>Event Info</h2>


  </div>
  <div class="span5">
  	<h2><a href="#">Link to a file</a></h2>
  	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  	
  </div>
</div>

app/views/pages/media.html.erb
<h1>Media</h1>
<p>Recent media apperances</p>
<p>You Tube Channel Goes Here</p>

app/views/pages/social.html.erb
<h1>Social Media</h1>

<div class="row">
  <div class="span1">Social Button</div>
  <div class="span1">Social Button</div>
  <div class="span1">Social Button</div>
</div>

Need some kind of padding here, 40-60px max

<div class="row">
  <div class="span1">Social Button</div>
  <div class="span1">Social Button</div>
  <div class="span1">Social Button</div>
</div>